application:
  puppeteer:
    headless: true
    user: env:WELLNESS_USER
    password: env:WELLNESS_PASSWORD
  typeorm:
    connectionOptions:
      type: sqlite
      database: wellness.sqlite
      synchronize: true

